# Generated by Django 3.0.8 on 2021-03-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
